version: "3.9"

services:
  airline_stub:
    image: "airline_stub:latest"
    ports:
      - "8081:8081"
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: "redis:6.2.6-alpine"
    command: redis-server
    expose:
      - 6379/tcp
