version: "3.9"


services:
  stub-service:
    image: "airline_stub:local_latest"
    ports:
      - "7001:7001"
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: "redis:6.2.6-alpine"
    command: redis-server
    expose:
      - 6379/tcp
